name: Build remote audio macOS

on:
  push:
    branches: [remote-audio-buffer]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install create-dmg
        run: |
          brew install node
          npm install --global create-dmg

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          set-env: true
          add-tools-to-path: true
          version: 6.11.2
          aqtsource: git+https://github.com/miurahr/aqtinstall.git@073e34d7c2ab4ae6961ed7cca690b3abd5ba5a7e

      - name: Build package
        run: bash scripts/generate-dmg.sh Release

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v6
        with:
          name: Moonlight-remote-audio-macos-${{ github.sha }}
          path: build/installer-Release/*.dmg
          compression-level: 0
          if-no-files-found: error
